
# Add this snippet to the top of your playbook. 
# # It will install python2 if missing (but checks first so no expensive repeated apt updates)
# # gwillem@gmail.com
#
- hosts: all
  gather_facts: False
     
  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    become: yes
